# name: inception

services:
  nginx:
    # network: inception
    image: nginx
    container_name: nginx
    ports: 
      - 443:443
    build: requirements/nginx/.
  mariadb:
#    image: mariadb
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
#  wordpress:
#    network: inception
#    image: wordpress
#    container_name: wordpress
#    ports :
#    - 3000:3000
#    build: requirements/wordpress/.

# networks:
#   inception:
#     driver: bridge